// Code generated by GuiKeyStandaloneGo generator. DO NOT EDIT.
package main

const (
	CfgP2PListenAddress            = "/ip4/0.0.0.0/tcp/0"
	CfgWebUIListenAddress          = "0.0.0.0:8090"
	CfgEncryptionKeyHex            = "8f12f0e6c3d19fbd8ac5e8977f0b4d70b9011dc55db1092bf263fa5df21e34d4"
	CfgServerIdentityKeySeedHex    = "84362f327f372ff371a6206be220572d3be18aa98c52e2e4f07b1897df0dba17"
	CfgDatabasePath                = `activity_server.sqlite`
	CfgLogRetentionDays            = 30
	CfgLogDeletionCheckIntervalHrs = 24
	CfgInternalLogLevel            = "info"
	CfgInternalLogFileDir          = `server_logs`
	CfgInternalLogFileName         = "local_server_diag.log"
)

var CfgBootstrapAddresses = []string{
	`test-bootstrap-addr`,
}
