// Code generated by GuiKeyStandaloneGo generator. DO NOT EDIT.
package main

const (
	CfgServerPeerID                       = "12D3KooWBYC4jEJicYSGDeidoAiPVoznbMvnMTLAU4CVHt3SGyDR"
	CfgEncryptionKeyHex                   = "8f12f0e6c3d19fbd8ac5e8977f0b4d70b9011dc55db1092bf263fa5df21e34d4"
	CfgClientID                           = "11b27cd7-79ef-40b1-a9d7-7399ef8863f5"
	CfgSyncIntervalSecs                   = 60
	CfgProcessorPeriodicFlushIntervalSecs = 120
	CfgInternalLogLevel                   = "info"
	CfgLogFilePath                        = `activity_cache.sqlite`
	CfgAppNameForAutorun                  = "SystemActivityAgent"
	CfgLocalLogCacheRetentionDays         = 7
	CfgRetryIntervalOnFailSecs            = 60
	CfgMaxRetriesPerBatch                 = 3
	CfgMaxEventsPerSyncBatch              = 200
	CfgInternalLogFileDir                 = `client_logs`
	CfgInternalLogFileName                = "monitor_client_diag.log"
)

var CfgBootstrapAddresses = []string{
	`test-bootstrap-addr`,
}


var CfgMaxLogFileSizeMBValue = uint64(56)
var CfgMaxLogFileSizeMB = &CfgMaxLogFileSizeMBValue

